USE MOVIE_STREAM;

INSERT INTO COUNTRY (Name, RegionId) VALUES ('Afghanistan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Algeria',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('American Samoa',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Angola',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Anguilla',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Argentina',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Armenia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Austria',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Azerbaijan',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Bahrain',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Bangladesh',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Belarus',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Bolivia',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Brazil',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Brunei',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Bulgaria',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Cambodia',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Cameroon',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Canada',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Chad',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Chile',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('China',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Colombia',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Congo',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Czech Republic',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Dominican Republic',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Ecuador',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Egypt',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Estonia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Ethiopia',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Faroe Islands',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Finland',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('France',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('French Guiana',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('French Polynesia',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Gambia',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Germany',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Greece',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Greenland',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Holy See (Vatican City State)',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Hong Kong',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Hungary',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('India',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Indonesia',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Iran',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Iraq',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Israel',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Italy',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Japan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Kazakstan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Kenya',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Kuwait',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Latvia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Liechtenstein',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Lithuania',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Madagascar',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Malawi',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Malaysia',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Mexico',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Moldova',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Morocco',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Mozambique',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Myanmar',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Nauru',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Nepal',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Netherlands',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('New Zealand',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Nigeria',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('North Korea',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Oman',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Pakistan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Paraguay',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Peru',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Philippines',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Poland',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Puerto Rico',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Reunion',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Romania',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Russia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Saint Vincent and the Grenadines',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Saudi Arabia',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Senegal',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Serbia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Slovakia',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('South Africa',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('South Korea',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Spain',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Sri Lanka',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Sudan',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Sweden',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Switzerland',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Taiwan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Tanzania',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Thailand',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Tonga',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Tunisia',10);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Turkey',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Turkmenistan',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Tuvalu',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Ukraine',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('United Arab Emirates',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('United Kingdom',9);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('United States',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Venezuela',7);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Vietnam',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Virgin Islands',6);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Yemen',8);
INSERT INTO COUNTRY (Name, RegionId) VALUES ('Zambia',10);

